### ISSUE TITLE
OSSL permissions

### ISSUE THREAD

**Issue by bikerchef50** [SatyrFarm/SatyrFarm#14]
**Describe the bug**
  OSSL Runtime Error: osMakeNotecard permission denied. Script creator is not in the list of users allowed to execute this function and prim owner also has no permission. (at event dataserver, part SF Fridge f82e86d4-4b71-45e5-99e8-42be9af44086 at <77.78922, 298.4718, 24.12735> in Muspelheim_2
The errors are 

I Have set these permissions on my OSSL.ini as follows: Allow_osMakeNotecard =            ${OSSL|osslParcelO}ESTATE_MANAGER,ESTATE_OWNER) 
As per the new update of the OpenSimulator server software 0.9.1.dev.391edb862e. 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10 Home
 - Browser [Google Chrome]
 - Version [Version 69.0.3497.100 (Official Build) (64-bit)]

**Additional context**

**Comment by opensimworld** [comment]
is the SF Fridge owner an estate manager or an estate owner?

**Comment by bikerchef50** [comment]
yes we are and she has  all rights I thought.
    On Wednesday, October 3, 2018, 4:55:52 AM CDT, OpenSimWorld <notifications@github.com> wrote:  
 
 
is the SF Fridge owner an estate manager ?

**Comment by opensimworld** [comment]
are you using the latest Opensim maybe? the OSSL settings have moved to the [OSSL] section instead of the [XEngine] section where they used to be. 

Check that your opensim reads the correct setting by running  "config get OSSL osMakeNotecard"  in your opensim console

**Comment by opensimworld** [comment]
closing this as it is a permissions issue
