### ISSUE TITLE
YEngine OutOfHeapException for Product script

### ISSUE THREAD

**Issue by punyauk** [SatyrFarm/SatyrFarm#17]
I've come across a bug in the product script - it's one of those that only shows on YEngine and also needs a particular set of circumstances to make it happen. That said, it causes memory leaks and I beleive will cause a region to crash eventually.  The issue is when the product moves to follow someone, each time there is a memory leak.  What I've seen is that when an NPC Farmer carries a bucket of water for a long time (because nothing needs watering) it will eventually cause this.   Anyway the change to code isn't that much - I checked with the code called **prod_gen_2** (from SatyrFarm Package v.2018.11.31) and it's to do with there being a return statement in the timer event (not entirely sure why this is an issue!)
Fixed code as follows:
```
    timer()
    {
        float t;
        if (followUser!= NULL_KEY)
        {    
            list userData=llGetObjectDetails(followUser, [OBJECT_NAME,OBJECT_POS, OBJECT_ROT]);
            if (llGetListLength(userData)==0)
            {
                followUser = NULL_KEY;
            }
            else
            {
                llSetKeyframedMotion( [], []);
                llSleep(0.2);
                list kf;
                vector mypos = llGetPos();
                vector size  = llGetAgentSize(followUser);
                uHeight = size.z;
                vector v = llList2Vector(userData, 1)+ <2.1, -1.0, 1.0> * llList2Rot(userData,2);
                t = llVecDist(mypos, v)/10;             
                if (t > 0.1)
                {
                    if (t > 5) t = 5;
                    vector vn = llVecNorm(v  - mypos );
                    vn.z=0;
                    //rotation r2 = llRotBetween(<1,0,0>,vn);
                    kf += v- mypos;
                    kf += ZERO_ROTATION;
                    kf += t;
                    llSetKeyframedMotion( kf, [KFM_DATA, KFM_TRANSLATION|KFM_ROTATION, KFM_MODE, KFM_FORWARD]);
                    t+=1;
                }
                else t = 5.0;
            }
        }
        else
        {
            refresh();
            t = 900.0;
        }
        llSetTimerEvent(t);
    }
```

**Comment by opensimworld** [comment]
this looks like a bug in YEngine then , perhaps add it to the opensim mantis?

**Comment by punyauk** [comment]
It's at http://opensimulator.org/mantis/view.php?id=8718
