### ISSUE TITLE
can u share IAR and OAR for try locally with my students

### ISSUE THREAD

**Issue by johnfelipe** [SatyrFarm/SatyrFarm#19]
Can u share IAR and OAR for review and tryout locally in a rural school without internet for review locally in a school room
Tnks

**Comment by johnfelipe** [comment]
Pls share me farm OAR

**Comment by BrinleyTaliesin** [comment]
Hi Felipe, I'm on a 2x2 varisim region, there is no way to provide only the farm, as an OAR would be the entire region, which includes many things other than farm :)

 

-Brinley

 
 

Sent: Wednesday, June 02, 2021 at 11:55 PM

**Comment by johnfelipe** [comment]
Is possible then iar files with objects included scripts?

**Comment by punyauk** [comment]
I have an oar that contains the farm shop that is found at hg.osgrid.org:80:mintor    This has the Quintonia edition of the SatyrFarm system.  You can download it from   https://u.pcloud.link/publink/show?code=kZxR11XZyuyr1VbOVuhxrHFb9vxqp5h33897

**Comment by johnfelipe** [comment]
.......... [Archiver]: Loaded 4864 assets, with 36 failures...
    .......... [Archiver]: Loaded 4964 assets, with 36 failures...
    .......... [Archiver]: Loaded 5064 assets, with 36 failures...
    .......... [Archiver]: Loaded 5164 assets, with 36 failures...
    .......... [Archiver]: Loaded 5264 assets, with 36 failures...
    .......... [Archiver]: Loaded 5364 assets, with 36 failures...
    .......... [Archiver]: Loaded 5464 assets, with 36 failures...
    .......... [Archiver]: Loaded 5564 assets, with 36 failures...
    .......... [Archiver]: Loaded 5763 assets, with 37 failures...

all that failures is normal?

**Comment by johnfelipe** [comment]
pls view this video, because is not working 

https://drive.google.com/file/d/1BEMq3f_IJST9_bznsWBrJeNyBUsOS-Ho/view?usp=drivesdk

pls pls share me another version without issues or failure i need for a workshop with farm objets and with all lsl and animation working
Tnks

**Comment by punyauk** [comment]
in the video you only show trying to get non Quintonia items - these are things I picked up elsewhere so not quite sure why they don't work, but anyway they are not part of the standard farm set.

Can you extract the boxes 1 to 12 and/or the pack with them all in?

**Comment by johnfelipe** [comment]
Do u have a other version?
Only for test....

**Comment by johnfelipe** [comment]
Can u share me latest ultimate version newst
Tnks

**Comment by opensimworld** [comment]
Hi @johnfelipe . Here is also an IAR package  of the satyrfarm package from opensimworld region: https://opensimworld.com/satyrfarm.iar

**Comment by punyauk** [comment]
I am in the process of getting the next version of my fork ready and when that is available I will also put out an IAR via the Quintonia.net website so do keep an eye out there.

**Comment by johnfelipe** [comment]
Wich Will be link?

**Comment by johnfelipe** [comment]
Pls share me link for keep in view
Tnks
