### ISSUE TITLE
IAR package corrupt

### ISSUE THREAD

**Issue by fly-man-** [SatyrFarm/SatyrFarm#20]
When trying to import the https://opensimworld.com/satyrfarm.iar file, it tells me that it's corrupt.

Any possibility that it gets refreshed, renewed so it works with the latest things from the repository ?

**Comment by opensimworld** [comment]
I updated the IAR with a new one. I hope it works, osgrid has been having problems with assets lately https://opensimworld.com/satyrfarm.iar

**Comment by fly-man-** [comment]
It works with the latest OS build

Thank you
