### ISSUE TITLE
Package at hg.osgrid.org:80:OpenSimWorld not up to date.

### ISSUE THREAD

**Issue by llaxton** [SatyrFarm/SatyrFarm#21]
aka Shelenn Ayres

Official package at hg.osgrid.org:80:OpenSimWorld is not up to date with the repository and does not include updated scripts and consistent naming within objects. Inconsistent naming also exists between this repository and OSW Farm pages. Some same named scripts actually serve different functions and should get unique names.

Forked this repository to begin updates for approximately 210 items to create an updated package for two grids using SF items.

Unable to locate Satyr created objects for the following scripts listed on https://opensimworld.com/library?view=5 : mine.lsl
power_charging_station.lsl
power_controller.lsl
power_electric_car.lsl
Where can I find these?

Any interest in my updated package for the hg.osgrid.org:80:OpenSimWorld or do you prefer I maintain my fork under a new name with same license?

**Comment by opensimworld** [comment]
Hi Shelenn! i think these items exist in the space area above the opensimworld island but honestly can't be sure (you can go there with the space shuttle) . The electricity part wasn't complete. 

Note that there is also another fork of satyrfarm, in the Mintor region https://opensimworld.com/hop/81990 where cnayl has done extensive modifications. you might want to take a look.

The "original" satyrfarm scripts in the main repository are meant to be as generic as possible. If you plan to make many specializations it's best to do it under a new name to avoid the confusion. I will happily host your  package in the opensimworld region.

**Comment by llaxton** [comment]
Hi! I am aware of the QSF project. No intent to work on their stuff with this issue or to create a new version of SF with content I created that is custom for Magnolia Gardens. The issue I want to help with is to get the standard generic SF package up to date using the scripts on the OSW SF page. Testing is nearly complete but I still have more updates to finish. I would then pass you a copy of the updated package to replace the one you have. That way anyone wanting to build upon SF can do so without needing to do all the work I have been doing.

**Comment by opensimworld** [comment]
OK great then it can be the new version of satyrfarm. Thanks for your work!

**Comment by Vattende** [comment]
That would be pretty nice. Each time started a new trial, i run into some issues after a while. So of course, having a pretty new package would be awesome for the community !
