### ISSUE TITLE
SF Farm is spamming Assetserver

### ISSUE THREAD

**Issue by ghost** [SatyrFarm/SatyrFarm#23]
**Describe the bug**
Running SF Farm on a grid is massively spamming the assetserver with notecards called "an_statusNC" and "storagenc"

**To Reproduce**
1. Run SF Farm for a while
2. Run the following sql statement when using fsasset: SELECT * FROM fsassets WHERE description = 'Script generated notecard' AND (name LIKE 'an_statusNC%' OR name LIKE 'storagenc%')

**Expected behavior**
Not spamming the asset server?

**Enviroment (please complete the following information):**
- OpenSimVersion : All OpenSim versions

**Comment by opensimworld** [comment]
I believe this is not an issue of the satyrfarm, but it was a problem with the Mintor version of the farm . According to Cnayl the problem has been solved. 

See here https://opensimworld.com/post/86666
