### ISSUE TITLE
Create a Centralized ConfigurationServer

### ISSUE THREAD

**Issue by IAmNolanPerry** [SatyrFarm/SatyrFarm#9]
Create a rezzable box that sends configuration to the components of the farm, Allows easy configuration of farm, and allow it to change, this can use the sfp notecard to decide which configuration thing is used

**Comment by opensimworld** [comment]
maybe provide details about this. what should it do ?

**Comment by uriesk** [comment]
Could be combined with an Update Box.
Click Box -> it updates everything inside storages, kitchens, whatever
Can then make some choices about if it should update/overwrite RECIPES and so on

**Comment by IAmNolanPerry** [comment]
Lets Start this, as a plugin maybe?
Here is the example script for it http://wiki.secondlife.com/wiki/Intra-Region_Update_Server

**Comment by DraconesForest** [comment]
Great idea

**Comment by IAmNolanPerry** [comment]
I plan to try this, expect to see a basic integration within 3-4 Beta Releases,

What I will do is make it to be 

1. A "Farm Terminal" is placed in each region/parcel(tbd)(1 Prim) that you want SF In
2. You add your SF Key to the config, and it sends a request to opensimworld for getting your Settings you want on all your items by default.
3. It receives the data from online, and then Broadcasts it to all your SF Items, or All SF Items(as needed)
